#!/bin/sh
DOTFILES_ROOT=$(cd $(dirname $0)/..; pwd)

for FILE in $(find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink)
do
	LINK_NAME="$HOME/.$(basename ${FILE%.*})"
	if [ ! -L $LINK_NAME ]; then
		ln -s $FILE $LINK_NAME
	fi
done
