#!/bin/sh
DOTFILES_ROOT=$(cd $(dirname $0)/..; pwd)

echo $DOTFILES_ROOT

for FILE in "$(find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink)"
do
	TARGET="$HOME/.$(basename ${FILE%.*})"
	ln -s $FILE $TARGET
done
